# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('somme_depart', models.FloatField()),
                ('somme_actuelle', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=140)),
                ('somme_depart', models.FloatField()),
                ('somme_actuelle', models.FloatField()),
            ],
        ),
    ]
